
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hngownaajjryouxkwmev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuZ293bmFhampyeW91eGt3bWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDU5MzYsImV4cCI6MjA2NTUyMTkzNn0.OL4zz4fkT_3WTt2L28CwcNFCoB7oDcNIctMoIVRZwmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
